version: "3.2"

services:

  proxy:
    image: nginx:1.14-alpine
    restart: always
    depends_on:
      - app
    volumes:
      - type: bind
        source: .
        target: /srv/www/app
      - type: bind
        source: ./nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  
  app:
    image: php-fpm
    restart: always
    volumes:
      - .:/srv/www/app

